Microsoft/workbooks

- Clients/Xamarin.Interactive.Client.Mac/Main.storyboard
Remove button color attribute.
As shown in the image below the button is blacked out.
Remove color attribute, button is now displayed.
Before
After
> [UI][mac] Remove background color to show NSAddTemplate

- Agents/Xamarin.Interactive.DotNetCore/DotNetCoreAgent.cs
- Agents/Xamarin.Interactive/CodeAnalysis/EvaluationContextInitializeRequest.cs
- Agents/Xamarin.Interactive/CodeAnalysis/TargetCompilationConfiguration.cs
- Agents/Xamarin.Interactive/Core/Agent.cs
- Clients/Xamarin.Interactive.Client/Compilation/Roslyn/FilteredDiagnostics.cs
- Clients/Xamarin.Interactive.Client/Compilation/Roslyn/RoslynCompilationWorkspace.cs
When using certain features with .NET Core (such as `dynamic`), or mixing PCLs and .NET Standard assemblies, warnings are produced that are purely cosmetic, like in #59.
Provide a way for agents to specify which warnings will be suppressed, pass the suppressions to Roslyn, and make sure that the client ignores suppressed diagnostics when reporting diagnostics.
Fixes #59.
> Client: Allow agents to provide default warning suppressions

- Build/Utility.targets
> Build: Don't include Policheck outputs when generating publication manifest

- Build/Xamarin.Build/MSBuild/UpdateInvertedDependencies.cs
- Build/git-repo.ps1
- dependencies.json
Because we can't use submodules for the proprietary repo that builds Xamarin.Android support, this annoying script does a poor job at emulating a submodule.
1. it operates on `GitRepo` objects from our `dependencies.json` (so at least everything is in one place)
2. it can inject a GitHub token into the URI, which comes from a secure variable in VSTS
3. if the ref being build in the main repo points to a tag, the ref in `dependencies.json` is discarded and the tag is used (e.g. the proprietary repo is tagged like the primary repo)
4. `-Update` can be passed to the script to reset the ref if it's already been checked out, but this is intentionally not default behavior
```bash
Build/git-repo.ps1 dependencies.json -Update -GitHubToken ********
```
This means that `UpdateInvertedDependencies` …
> Add git-repo.ps1 to fetch the right ref for the proprietary repo

- Clients/Xamarin.Interactive.Client/ClientApp/renderers/string-renderer.ts
This fixes a regression introduced in 1.3 around rendering C# string literals that contain emoji.
> string-renderer.ts: use correct high surrogate start value

- Clients/Xamarin.Interactive.Client/Compilation/Roslyn/MonoScriptCompilationPatcher.cs
- Clients/Xamarin.Interactive.Client/Compilation/Roslyn/RoslynCompilationWorkspace.cs
- Tests/Workbooks/Regression/Custom Attribute Types.workbook
Custom attributes (either from libraries or defined in the workbook itself) would cause the CLR
to throw `TypeLoadException` (with an empty type name!) when trying to load the type to create
the custom attribute instance, somewhere deep inside COM bits (I tracked it to CreateCaObject,
which is an internal call into the CLR).
Changing our assembly name prefix to not have any spaces fixed the initial submission (no
`TypeLoadException`, the correct output from the sample workbook in #104), but subsequent
submissions would throw `TypeLoadException` (this time with a non-bogus type name!) because
the assembly name had changed. 
The 2nd commit in the series fixes that as well, by improving the detection for when the assembly name has ended—the `+` used for nested classes wasn't being detected. …
> Compilation: Fix custom attributes using types defined in the workbook

- Clients/Xamarin.Interactive.Client.Mac/CoordinateMappers/iOSSimulatorCoordinateMapper.cs
We only know it's a 5s in the case of Workbooks.
First part of fixing https://github.com/Microsoft/workbooks/issues/24.
Next will be passing more info to the client about what device was
launched.
> Allow iOS coordinate mapper to work for Inspector and non-5s devices

- Clients/Xamarin.Interactive.Client.Windows/Resources.xaml
- Clients/Xamarin.Interactive.Client.Windows/Themes/High Contrast.xaml
- Clients/Xamarin.Interactive.Client.Windows/Themes/Light.xaml
- Clients/Xamarin.Interactive.Client.Windows/Xamarin.Interactive.Client.Windows.csproj
The package dialog UI (and theoretically, any other MahApps dialog UI) would not draw correctly after the OS was locked and unlocked--the UI would be working, but would be completely transparent.
Update MahApps to pull in the upstream bug fix (MahApps/MahApps.Metro#2734), and fix some small a11y/theming bugs that cropped up after the update.
Fixes #115.
> Windows: Fix package dialog UI not drawing correctly after unlock

- Clients/Xamarin.Interactive.Client.Mac/NewWorkbookViewController.cs
- Clients/Xamarin.Interactive.Client.Windows/Views/NewWorkbookWindow.xaml.cs
- Clients/Xamarin.Interactive.Client/Client/ViewControllers/NewWorkbookItem.cs
- Clients/Xamarin.Interactive.Client/Client/ViewControllers/NewWorkbookViewController.cs
- Clients/Xamarin.Interactive.Client/Client/ViewControllers/WorkbookAppViewController.cs
- Clients/Xamarin.Interactive.Client/Preferences/Prefs.cs
Sets the agent type when either the broader agent grouping or the more specific agent type within the grouping is set and changes constructors to use field setters instead of property setters to avoid side effects as necessary so that we don't update the preference all the time when constructing the items/controller.
Fixes #58.
> Client: Store last used workbook app and select it on startup.

- Clients/Xamarin.Interactive.Client.Mac/AppDelegate.cs
- Clients/Xamarin.Interactive.Client.Mac/Main.storyboard
- Clients/Xamarin.Interactive.Client.Windows/Views/MenuManager.cs
- Clients/Xamarin.Interactive.Client/ClientApp.cs
- Clients/Xamarin.Interactive.Client/IssueReport.cs
- Clients/Xamarin.Interactive.Client/Markdown/MarkdownTable.cs
- Clients/Xamarin.Interactive.Client/Xamarin.Interactive.Client.csproj
> Add "Report an Issue" help menu item

- Agents/Xamarin.Interactive/InteractiveInstallation.cs
- Agents/Xamarin.Interactive/InteractiveInstallationPaths.cs
- Build.proj
- Build/Metadata.targets
- Clients/Xamarin.Interactive.Client.Mac/AppDelegate.cs
- Clients/Xamarin.Interactive.Client.Mac/Main.storyboard
- Clients/Xamarin.Interactive.Client.Mac/Preferences/PreferencesWindowController.cs
- Clients/Xamarin.Interactive.Client.Mac/Xamarin.Interactive.Client.Mac.csproj
- Clients/Xamarin.Interactive.Client.Windows/App.xaml.cs
- Clients/Xamarin.Interactive.Client.Windows/Views/MenuManager.cs
- Clients/Xamarin.Interactive.Client.Windows/Views/OptionsWindow.xaml
- Clients/Xamarin.Interactive.Client.Windows/WindowsClientApp.cs
- Clients/Xamarin.Interactive.Client/ClientApp.cs
- Clients/Xamarin.Interactive.Client/WorkbookAppInstallation.cs
- Package/Mac/Xamarin.Inspector.Mac.nuspec
- Package/Windows/Xamarin.Inspector.Windows.nuspec
- Tests/Xamarin.Interactive.Tests.InspectorSupport.Mac/Main.cs
This is the first step to fixing https://github.com/Microsoft/workbooks/issues/23.
Both `Xamarin Workbooks.app` and `Xamarin Inspector.app` now have all files they need directly in the app bundle, instead of depending on `/Library/Frameworks/Xamarin.Interactive.framework`. Specifically, forms support and (in the case of Inspector) agent assemblies have been moved to `SharedSupport/Agents`. We can remove `Xamarin.Interactive.framework` as soon as we're ready to drop 15.5 support.
`updateinfo` and `buildinfo` have moved from `Resources` to `SharedSupport` within the app bundles.
Our package build now also generates a `Xamarin.Inspector.Mac` NuGet package, which can be consumed by the VSmac Inspector extension, so that the extension will no longer require a compatible installation of Xamarin …
> Bundle Inspector clients into NuGet packages for IDE extensions

- Build.proj
Copy after signing instead of during `Install`. This matches up better
with the Windows target, too.
> Mac: Ensure Inspector.app in nupkg is signed

- Agents/Xamarin.Interactive.Forms.Android/Xamarin.Interactive.Forms.Android.csproj
- Agents/Xamarin.Interactive.Forms.iOS/Xamarin.Interactive.Forms.iOS.csproj
- Agents/Xamarin.Interactive.Forms/Xamarin.Interactive.Forms.csproj
- Clients/Xamarin.Interactive.Client/Client/ClientSession.cs
- Clients/Xamarin.Interactive.Client/Compilation/CompilationWorkspaceFactory.cs
- Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs
- Package/Windows/AndroidAgentAppAssemblies.wxs
- WorkbookApps/Xamarin.Workbooks.Android/Properties/AndroidManifest.xml
- WorkbookApps/Xamarin.Workbooks.Android/Xamarin.Workbooks.Android.csproj
- dependencies.json
Bump our enforced Xamarin.Forms version to the latest stable version, and fix inspection of Xamarin.Forms apps.
Read each commit individually for maximum clarity.
> Forms: Bump to latest stable (2.5.0).

- Clients/Xamarin.Interactive.Client/CodeAnalysis/Monaco/SignatureHelpProvider.cs
- Clients/Xamarin.Interactive.Client/RoslynInternals/InternalExtensions.cs
* Correct behavior with nested method calls (https://github.com/Microsoft/workbooks/issues/17)
* Prevent showing static methods in instance contexts, and vice versa (https://github.com/Microsoft/workbooks/issues/64)
* Hide inaccessible method overloads (for example, the parameterless `System.Text.RegularExpressions.Regex`
constructor)
> Signature help bugfixes

- Clients/Xamarin.Interactive.Client/Rendering/Renderers/HtmlRendererBase.cs
Generics get messed up by this--the generic brackets end up creating
a new tag (or multiple tags) for the generic parameters. This affects
generic collections, anonymous types, value tuples, etc., when displayed
in object members mode/enumerable mode.
Fixes #138.
> Client: Make sure to escape type names for HTML.

- Build.proj
- Clients/Xamarin.Interactive.Client.Mac/AppDelegate.cs
- Clients/Xamarin.Interactive.Client/ClientApp.cs
- Clients/Xamarin.Interactive.Client/CommandLineTool/Driver.cs
- Package/Mac/Scripts/postinstall
- Package/Mac/workbook
Still generates the wrapper script as part of `postinstall`, but instead of writing it directly into `/usr/local/bin`, it's written into our bundle and that path is added to `/etc/paths.d`.
Fixes #56.
> Mac: Use paths.d to get workbook CLI tool into PATH.

- Agents/Xamarin.Interactive/Versioning/ReleaseVersion.cs
- Build/Metadata.targets
- Build/Xamarin.Build/MSBuild/ReleaseVersion.cs
- Build/Xamarin.Build/Xamarin.Build.targets
- Tests/Xamarin.Interactive.Tests/ReleaseVersionTests.cs
Previously this was created in `Metadata.targets` along with
`ReleaseVersion_SemVer`, but I failed to realize that this property was
meant to be consumed and then overwritten later in
`Xamarin.Build.targets`.
Moved `ReleaseVersion_SemVerNuGetSafe` to be generated there as well so
it can benefit from `ReleaseVersion` logic that excludes build numbers
when they are not needed. And also because it always should have been
there.
> Build: Change where ReleaseVersion_SemVerNuGetSafe gets created

- Tools/InstallerVerifier/InstallerVerifier.csproj
- Tools/InstallerVerifier/Program.cs
- Tools/InstallerVerifier/WinTrust.cs
Do signature verification in proces via the WinTrustVerify API using the authenticode policy provider and provider flags that match the results of `signtool verify /pa`.
This makes signature verification go from two minutes to five seconds.
* Fixes #149
* Fixes #150
> InstallerVerifier: use WinTrustVerify

- Clients/Xamarin.Interactive.Client/Preferences/Prefs.cs
- Clients/Xamarin.Interactive.Client/Telemetry/Client.cs
- Clients/Xamarin.Interactive.Client/Telemetry/Events/AppSessionStart.cs
Disassociate it from the anonymous persistent user GUID and expunge it from the preference store.
> Only submit the app.sessionStart telemetry object

- Clients/Xamarin.Interactive.Client.Mac/AppDelegate.cs
- Clients/Xamarin.Interactive.Client/Client/ClientSession.cs
- Clients/Xamarin.Interactive.Client/CommandLineTool/Driver.cs
- Tests/Workbooks/Regression/Weird %25 Name.workbook
- Tests/Workbooks/Regression/Weird %Name.workbook
The console driver was broken because the previous fix was incomplete—it only worked when you were in a built checkout of the repository. The new fix correctly takes advantage of the fact that the console driver _is_ the application, and uses its own location to look up the right thing to launch.
The recent menu on macOS was broken for files with spaces in the name—we were using the wrong NSUrl constructor. Using the right one does the correct thing without any additional hacking around. Added some workbooks with odd names (%-encoded, in particular) to make sure that we can open things that turn into weird URLs.
> Client/Mac: Fix opening workbooks from console driver & recent menu

- Clients/Xamarin.Interactive.Client/Camera/Dolly.cs
Avoid potential problem if a motion event is delivered before the first press event
in wpf by ensuring the the previous projection is valid.
Fixes #86
> Make sure the previous projection is valid before computing the rotation

- Clients/Xamarin.Interactive.Client.Windows/ViewModels/InspectTreeNode3D.cs
- Clients/Xamarin.Interactive.Client.Windows/Views/InspectTreeView.xaml.cs
In certain cases android views that are in the visual tree but outside of the visible region can retain negative values. Make the wpf 3d view slightly more robust by handing this case without an exception
> Don't attempt to render empty views

- Clients/Xamarin.Interactive.Client/PropertyEditor/InteractivePropertyInfo.cs
This fixes a couple of corner cases in for our representations in the property editor.
* For some properties we return messages not values, render those.
* The generic cast can fail where our representation has a padded value.  Use Convert.ChangeType instead.
> Property editor improvements.

- Build.proj
For now, makes it easier to run `/t:Package` without having access to provisionator. We should probably make this more automatic/magic/whatever in a second pass.
> Build.proj: prefer $(MSBuildThisFileDirectory)nuget.exe

- Agents/Xamarin.Interactive/Serialization/InteractiveJsonSerializerSettings.cs
- Clients/Xamarin.Interactive.Client.Web/ClientApp/evaluation.ts
- Clients/Xamarin.Interactive.Client.Web/ClientApp/renderers/ImageRenderer.tsx
- Clients/Xamarin.Interactive.Client.Web/ClientApp/renderers/ToStringRenderer.tsx
- Clients/Xamarin.Interactive.Client.Web/ClientApp/renderers/VerbatimHtmlRenderer.tsx
Short type names are problematic if we ever need to go back to .NET from TypeScript. We don't have too many type name checks on the TS side so just suck it up and check full type names.
> Serialization: use full type names everywhere

- Clients/Xamarin.Interactive.MTouch/MTouchSdkTool.cs
Mimics VSmac behavior.
Fixes https://github.com/Microsoft/workbooks/issues/249.
> Prefer /Applications/Xcode.app to xcode-select path

- WorkbookApps/WorkbookApp.targets
X.A started shipping these into the framework reference assembly directory on Windows
at some point (they started showing up in our Appveyor builds randomly) and they 
shouldn't be shipped--they're used during the build process to build an APK, but aren't
expected to be used by anyone writing Xamarin.Android apps.
> Build: Remove some Android assemblies that shouldn't be shipped.

- Agents/Xamarin.Interactive.Mac/NativeExceptionHandler.cs
- Agents/Xamarin.Interactive.iOS/NativeExtensions.cs
- Agents/Xamarin.Interactive/CodeAnalysis/Evaluating/EvaluationContextManager.cs
- Agents/Xamarin.Interactive/CodeAnalysis/Resolving/DllMap.cs
- Agents/Xamarin.Interactive/CodeAnalysis/TargetCompilationConfiguration.cs
- Agents/Xamarin.Interactive/Runtime.cs
- Agents/Xamarin.Interactive/Serialization/InteractiveJsonSerializerSettings.cs
- CodeAnalysis/Xamarin.Interactive.CodeAnalysis.Tests/DllMapTests.cs
- docs/Xamarin.Interactive.api.cs
This is a managed implementation of Mono's DLL mapping support that allows for platform-specific mapping of native libraries and symbols within them.
We will use this as a basis for providing better native library loading support for NuGet in .NET Core in particular via `AssemblyLoadContext.LoadUnmanagedDll(string unmanagedDllName)`.
Unfortunately `AssemblyLoadContext` does not support symbol mapping, but it is implemented in the `DllMap` in this commit should the ability be introduced in the future.
This is likely a good basis for #204.
> CodeAnalysis: Resolving: add Mono's DllMap support

- Agents/Xamarin.Interactive.Mac/NativeExceptionHandler.cs
- Agents/Xamarin.Interactive.iOS/NativeExtensions.cs
- Agents/Xamarin.Interactive/API/Xamarin.Interactive.api.cs
- Agents/Xamarin.Interactive/CodeAnalysis/Resolving/DllMap.cs
- Agents/Xamarin.Interactive/Runtime.cs
> Runtime and DllMap backport for 1.4

- Package/Windows/AndroidAgentAppAssemblies.wxs
- WorkbookApps/Xamarin.Workbooks.Android/Build.targets
- build.proj
At least provide a better and faster error message when restore isn't
run first.
Ugh. https://github.com/Microsoft/msbuild/issues/2455
> build: force separate Restore and Build targets

- Agents/Xamarin.Interactive/Collections/PropertyList.cs
Finally just bring over this old PropertyList implementation from the Banshee days. Freshly updated to be internal, with slightly better immutability, and use some more modern C# constructs.
Ideally we would just depend on larger one from Xamarin.MacDev, but that entire library needs to be split up a bit and actually published on NuGet.
For now this should get us XML and Binary format support without having to shell out to plutil, which is known to be problematic as sometimes it freezes/never exits.
> Hello plist my old friend

- Agents/Xamarin.Interactive.Forms.Android/Xamarin.Interactive.Forms.Android.csproj
- Agents/Xamarin.Interactive.Forms.iOS/Xamarin.Interactive.Forms.iOS.csproj
- Agents/Xamarin.Interactive.Forms/Xamarin.Interactive.Forms.csproj
- CodeAnalysis/Xamarin.Interactive.CodeAnalysis/CodeAnalysis/WorkspaceConfiguration.cs
- CodeAnalysis/Xamarin.Interactive.CodeAnalysis/NuGet/InteractivePackageManager.cs
- Package/Windows/AndroidAgentAppAssemblies.wxs
- WorkbookApps/Xamarin.Workbooks.Android/Xamarin.Workbooks.Android.csproj
- dependencies.json
During testing, we found some issues with XF integration and iOS, but these problems exist on 1.4.0, and are not regressions caused by this upgrade.
>  Bump Xamarin.Forms to 3.0.0.482510

- Agents/Xamarin.Interactive/InteractiveInstallation.cs
- ClientIntegrations/Xamarin.Workbooks.Client.iOS/iOSAgentProcess.cs
- Clients/Xamarin.Interactive.Client.Mac.SimChecker/Program.cs
- Clients/Xamarin.Interactive.Client.Mac.SimChecker/Xamarin.Interactive.Client.Mac.SimChecker.csproj
- Clients/Xamarin.Interactive.Client.Mac/AgentProcesses/iOSAgentProcess.cs
- Clients/Xamarin.Interactive.MTouch/MTouchSdkTool.cs
- Package/Windows/ToolsFiles.wxs
On my system, I frequently see `plutil` requests hang for no apparent reason. Fixed process execution in `MTouchSdkTool` to have a proper async flow and logging, and to support timeouts and limited retries. Ideally, `Exec` would be updated to support these features, and `MTouchSdkTool` would just rely on that class. And ideally we would not have to call `plutil` at all. We can address these down the road.
Also fixed a mistake in the `DefaultSdkRoot` path that caused issues for Windows.
>  Fix potential hangs loading iOS workbooks

- build/Utility.targets
This document comes straight from CELA and does not need to be checked.
> Policheck: Exclude license.rtf

- Clients/Xamarin.Interactive.Client/Rendering/Renderers/CSharpTextRenderer.cs
Inner exceptions can't be expanded without this fix.
> Client: Output correct click handler for exception toggles.

- .vsts-ci.yml
- build/select-mono.sh
The public VSTS macOS pool has many versions of Mono installed, but currently the selected/active version in PATH is older than required to support building .NET Core 2.1 under the system/Mono MSBuild.
Select the latest installed version in VSTS to fix the build.
> build: add select-mono.sh to run in VSTS hosted pool

- CodeAnalysis/Xamarin.Interactive.CodeAnalysis/CodeAnalysis/Resolving/NativeDependencyResolver.cs
Because we ship a 64-bit .NET Core agent on Windows now.
This prevents an NRE as well.
> Win: Remove obsolete checks in NativeDependencyResolver

- Clients/Xamarin.Interactive.Client.Windows/Views/MenuManager.cs
Reported as part of https://github.com/Microsoft/workbooks/issues/459.
See also https://stackoverflow.com/questions/12769264/openclipboard-failed-when-copy-pasting-data-from-wpf-datagrid.
> Win: Work around potential clipboard crash

- ClientIntegrations/Xamarin.Workbooks.Client.iOS/iOSAgentProcess.cs
- Clients/Xamarin.Interactive.Client.Mac.SimChecker/Program.cs
- Clients/Xamarin.Interactive.Client.Mac/AgentProcesses/iOSAgentProcess.cs
- Clients/Xamarin.Interactive.MTouch/MTouchListSimXml.cs
- Clients/Xamarin.Interactive.MTouch/MTouchSdkTool.cs
Client integrations now have access to all available devices, as well.
This changes SimChecker output to be incompatible with Workbooks < 1.2
(when Windows still required a Workbooks install on the Mac host).
> iOS: Prefer iPhone X to iPhone 5s

- CodeAnalysis/Xamarin.Interactive.CodeAnalysis/CodeAnalysis/Resolving/NativeDependencyResolver.cs
Similar to https://github.com/Microsoft/workbooks/pull/467, this repeated NRE was really slowing down client startup on Windows when debugging.
Only impacts `master`.
> Resolving: Fix another NRE

- Build.proj
Inspector extension tries to load this; good idea to ship regardless.
> Inspector: Add buildinfo to Windows nupkg (1.4)

- Clients/Xamarin.Interactive.Client.Desktop/ViewInspector/InspectTreeRoot.cs
- Clients/Xamarin.Interactive.Client.Desktop/ViewInspector/ViewInspectorViewModel.cs
- Clients/Xamarin.Interactive.Client.Windows/AgentSessionWindow.xaml.cs
This was accidentally deleted from the Mac client in 1.4.0.
Force callers to go through `SetSelectedView` method to make the flow
safer and avoid situations where `SetSelectedView` got called an extra
time.
Fixes: https://github.com/Microsoft/workbooks/issues/456
> Client: Set selectedView in shared code

- ClientIntegrations/Xamarin.Workbooks.Client.iOS/iOSAgentProcess.cs
- Clients/Xamarin.Interactive.Client.Mac.SimChecker/Program.cs
- Clients/Xamarin.Interactive.Client.Mac/AgentProcesses/iOSAgentProcess.cs
- Clients/Xamarin.Interactive.MTouch/MTouchListSimXml.cs
- Clients/Xamarin.Interactive.MTouch/MTouchSdkTool.cs
Client integrations now have access to all available devices, as well.
This changes SimChecker output to be incompatible with Workbooks < 1.2
(when Windows still required a Workbooks install on the Mac host).
>  iOS: Prefer iPhone X to iPhone 5s 

- Clients/Xamarin.Interactive.Client/Telemetry/Client.cs
Unfortunately I didn't notice this before 1.4.2 so we still need to send a custom Machine ID property. We should have never had that as a custom property and used the user context as intended. Sigh.
> Telemetry: use machine ID as user context for app insights

- Agents/Xamarin.Interactive/CodeAnalysis/EvaluationContextInitializeRequest.cs
- Clients/Xamarin.Interactive.Client/Compilation/CompilationWorkspaceFactory.cs
1. Open Workbooks
2. Create a XF iOS workbook
3. Create a non-XF iOS workbook
The second workbook, for whatever reason, doesn't set a PEImage for the
global state assembly, so the client tries to resolve it from a different
location, leading to an exception.
Cache to avoid this. Will be nice when this reflection loading can go away.
> Client: Cache global state assemblies by name

- Clients/Xamarin.Interactive.Client.Windows/App.config
- Clients/Xamarin.Interactive.Client.Windows/Xamarin.Interactive.Client.Windows.csproj
https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/510901-BCL%20Apps%20targeting%20.NET-4.6.1%20that%20use%20.NET%20Standard%20libraries%20might%20be%20broken%20when%20running%20on%20.NET%204.7.1.md
.NET 4.7.1 shipped with a bug where a .NET 4.6.1 app like ours, with
binding redirects generated for .NET Standard 2.0 references, would fail to
load certain types.
Users should really update their framework to get the fix, but we cannot
count on that. So, since .NET 4.7.1 and newer don't need those binding
redirects anymore, we can "simply" remove them on that platform.
This turns off `AutoGenerateBindingRedirects`, and splits them into those
actually needed on all framework versions, and those that are generated for
any .NET 4.6.1 app that references a .NET Standard …
> Win: Fix running on .NET 4.7.1
